#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

picom &
dunst &

nvidia-settings --load-config-only

xsetroot -cursor_name left_ptr

bspc monitor -d 하나 둘 셋 넷 다섯 여섯 일곱 여덟
bspc config border_width         0
bspc config window_gap          15

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc config focus_follows_pointer true
 
bspc rule -a discord desktop='^4'

discord &

feh --bg-center ~/Pictures/wallpaper.jpg

~/.config/polybar/launch.sh &
~/scripts/spotify/launchlistener.sh &
